server:
  port: ${EUREKA_SERVER_PORT}

eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME}

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST_NAME}:${EUREKA_SERVER_PORT}/eureka/
  server:
    eviction-interval-timer-in-ms: 10000
