server:
  port: 9000

eureka:
  instance:
      hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  server:
    eviction-interval-timer-in-ms: 10000
