server:
  port: 8123

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: master
